<NewScreen>:

    name: 'newscreen'
    FloatLayout:
        size_hint: None, None
    Label:
        text: 'Welcome to the New Screen!'
        center_x: root.width * 0.5
        center_y: root.height * 0.6

    DPEAButton:
        id: test_button6
        text: 'back to mainscreen'
        size: 100, 100
        x: root.width * 0.5
        y: root.height * 0.25
        color: 0.5, 1, 0.7, 1
        on_press: root.goback(test_button6)